spring:
  application:
    name: pnc-segundo-parcial-00011223

  datasource:
    url: jdbc:postgresql://localhost:5432/parcial
    password: hola
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true